#!/usr/bin/env python3
"""Build docs/seo/topics-next-250.json: 250 net-new intents vs the live corpus.

Rejects any slug that already exists as a post file, a held-duplicate, or a
plan-50 slug collision with live. Token-overlap against live slugs is flagged
and dropped above a Jaccard of 0.55.
"""
from __future__ import annotations

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
POSTS = ROOT / 'packages/web/src/app/blog/posts'
HELD = ROOT / 'docs/seo/held-duplicates'
OUT = ROOT / 'docs/seo/topics-next-250.json'
PLAN50 = ROOT / 'docs/seo/plan-50-2026-08-27.json'
BOTS = ROOT / 'seed-bots'

STOP = {
    'the', 'a', 'an', 'and', 'or', 'for', 'to', 'of', 'in', 'with', 'that', 'your',
    'you', 'how', 'what', 'grok', 'bot', 'bots', 'is', 'it', 'can', 'do', 'does',
    'not', 'on', 'as', 'are', 'be', 'without', 'from', 'who', 'which', 'a', 'vs',
}


def toks(s: str) -> set[str]:
    return {w for w in re.sub(r'[^a-z0-9 ]', ' ', s.lower()).split() if len(w) > 2 and w not in STOP}


def jaccard(a: set[str], b: set[str]) -> float:
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def live_slugs() -> set[str]:
    return {p.stem for p in POSTS.glob('*.ts') if p.stem != 'index'}


def held_slugs() -> set[str]:
    return {p.stem for p in HELD.glob('*.ts')}


def article(slug, title, keyword, category, cluster, priority, why_new, distinct_from=''):
    return {
        'slug': slug,
        'title': title,
        'keyword': keyword,
        'category': category,
        'cluster': cluster,
        'priority': priority,
        'status': 'planned',
        'why_new': why_new,
        'distinct_from': distinct_from,
    }


def from_plan50() -> list[dict]:
    raw = json.loads(PLAN50.read_text())
    out = []
    for a in raw['articles']:
        slug = a['slug']
        title = a['title']
        track = a.get('track', 'ops')
        cat = a.get('category', 'Guide')
        cluster = {
            'problem-intent': 'problem',
            'orphan-bot': 'jobs',
            'ops-gap': 'ops',
            'decision': 'decision',
            'migration': 'migration',
        }.get(track, track)
        kw = slug.replace('-', ' ').replace('grok bot', 'grok bot')
        why = a.get('why_new') or a.get('bot') or track
        bot = a.get('bot')
        if bot:
            why = f"Catalog bot {bot}: {why if isinstance(why, str) else 'no dedicated article yet.'}"
        pri = 1 if track in ('problem-intent', 'migration') else 2
        out.append(article(slug, title, kw[:80], cat, cluster, pri, str(why)))
    return out


def extra_topics() -> list[dict]:
    """199+ more unique intents. Keep each why_new naming the live twin it is not."""
    A = article
    return [
        # --- catalog jobs still without a page ---
        A('never-let-the-grocery-bot-check-out', 'A Grocery Bot That Fills the Cart and Never Pays',
          'grok bot grocery list', 'Tutorial', 'jobs', 2,
          'grocery-autopilot: cart only. Distinct from amazon-cart and bargain-scout (listings, never bid).',
          'watch-listings-without-bidding'),
        A('amazon-cart-that-never-buys', 'Build an Amazon Cart From a Spec Sheet and Stop Before Buy Now',
          'grok bot amazon cart', 'Tutorial', 'jobs', 2,
          'amazon-cart-builder. Distinct from bargain-scout (watch listings) and grocery-autopilot.',
          'watch-listings-without-bidding'),
        A('flight-check-in-reminder-never-books', 'Watch a Flight and Remind, Never Change or Buy the Ticket',
          'grok bot flight check in', 'Tutorial', 'jobs', 2,
          'flight-check-in. Distinct from grok-bot-calendar-manager (propose never book meetings).',
          'grok-bot-calendar-manager'),
        A('personal-cfo-brief-never-moves-money', 'A Weekday Money Brief That Never Moves a Dollar',
          'grok bot personal cfo', 'Tutorial', 'jobs', 1,
          'personal-cfo. Distinct from grok-bot-for-accountants (books vs filings) and expense-manager (receipts).',
          'grok-bot-for-accountants,grok-bot-expense-manager'),
        A('subscription-pruner-never-cancels', 'Flag Unused Subscriptions and Never Click Cancel',
          'grok bot cancel subscriptions', 'Tutorial', 'jobs', 2,
          'subscription-pruner. Distinct from grok-bot-to-subscription-audit (audit pack) and cancellation-advisor.',
          'grok-bot-to-subscription-audit'),
        A('when-to-cancel-a-subscription-and-who-clicks', 'Advise a Cancel, Then Hand the Button Back',
          'grok bot subscription cancellation', 'Guide', 'jobs', 3,
          'subscription-cancellation-advisor. Distinct from pruner (inventory) and to-subscription-audit.',
          'subscription-pruner-never-cancels'),
        A('podcast-summary-that-never-publishes-show-notes', 'Summarize a Podcast Episode Into Private Notes',
          'grok bot podcast summary', 'Tutorial', 'jobs', 2,
          'podcast-summarizer. Distinct from grok-bot-to-newsletter-digest and youtube-manager (never publish).',
          'grok-bot-to-newsletter-digest,grok-bot-youtube-manager'),
        A('podcast-clips-without-posting-them', 'Cut Clip Candidates and Never Upload Them',
          'grok bot podcast clips', 'Tutorial', 'jobs', 3,
          'podcast-clip-desk. Distinct from podcast-summarizer (notes) and youtube-manager (YouTube Studio).',
          'podcast-summary-that-never-publishes-show-notes'),
        A('youtube-transcript-desk-never-comments', 'Index YouTube Transcripts You Already Saved, Never Comment',
          'grok bot youtube transcript', 'Tutorial', 'jobs', 2,
          'youtube-transcript-desk. Distinct from grok-bot-for-youtube-creators (role) and youtube-manager (listing drafts).',
          'grok-bot-youtube-manager,grok-bot-for-youtube-creators'),
        A('viral-tweet-scout-never-posts', 'Explain Why a Post Spread, Then Draft Nothing',
          'grok bot twitter research', 'Tutorial', 'jobs', 2,
          'viral-tweet-scout is read-only, no draft copy. Distinct from grok-bot-to-social-scheduling (queue).',
          'grok-bot-to-social-scheduling'),
        A('x-account-crew-never-tweets', 'Prep an X Shift Pack That Cannot Hit Post',
          'grok bot twitter crew', 'Playbook', 'jobs', 3,
          'x-account-crew. Distinct from viral-tweet-scout (research) and social-scheduling.',
          'viral-tweet-scout-never-posts'),
        A('linkedin-signal-watch-never-connects', 'Watch Public LinkedIn Signals and Never Send a Connect',
          'grok bot linkedin signals', 'Tutorial', 'jobs', 2,
          'linkedin-signal-watch. Distinct from talent-scout (people bar) and icp-roster (plan-50).',
          'grok-bot-talent-scout,icp-roster-reverified-weekly'),
        A('competitor-ad-watch-never-launches-ads', 'Clip Competitor Ads Into a Folder, Never Launch Yours',
          'grok bot competitor ads', 'Tutorial', 'jobs', 2,
          'competitor-ad-watch. Distinct from grok-bot-paid-media (own spend watch, never change bids).',
          'grok-bot-paid-media,grok-bot-to-competitor-monitoring'),
        A('competitor-pricing-watch-never-reprices', 'Log a Competitor Price With a Source, Never Change Yours',
          'grok bot competitor pricing', 'Tutorial', 'jobs', 2,
          'competitor-pricing-watch. Distinct from competitor-monitoring hub and paid-media.',
          'grok-bot-to-competitor-monitoring,grok-bot-evidence-rules'),
        A('competitor-switch-scout-never-emails-their-customers', 'Find Public Switch Stories, Never Message Those Customers',
          'grok bot competitor switch', 'Tutorial', 'jobs', 3,
          'competitor-switch-scout. Distinct from lead-research and sales-outbound (never send).',
          'grok-bot-to-lead-research,grok-bot-sales-outbound'),
        A('competitor-website-watch-could-not-compute', 'Diff a Competitor Homepage and Allow a Quiet Week',
          'grok bot competitor website watch', 'Tutorial', 'jobs', 2,
          'competitor-website-watch. Distinct from browser-broke (symptom) and false-positives (always-red).',
          'grok-bot-browser-broke,grok-bot-false-positives'),
        A('content-ideas-that-never-become-posts', 'Rank Content Ideas Against a Brief, Never Schedule Them',
          'grok bot content ideas', 'Tutorial', 'jobs', 2,
          'content-idea-generator. Distinct from to-content-calendar and youtube-manager.',
          'grok-bot-to-content-calendar'),
        A('marketing-calendar-sync-never-publishes', 'Diff the Marketing Calendar File, Never Hit Publish',
          'grok bot marketing calendar', 'Tutorial', 'jobs', 3,
          'marketing-calendar-sync. Distinct from to-content-calendar (plan) and social-scheduling.',
          'grok-bot-to-content-calendar,grok-bot-to-social-scheduling'),
        A('marketing-os-audit-never-rewrites-the-stack', 'Audit the Marketing Stack on Paper, Never Disconnect a Tool',
          'grok bot marketing audit', 'Playbook', 'jobs', 3,
          'marketing-os-auditor. Distinct from crm-hygiene and paid-media.',
          'grok-bot-crm-hygiene'),
        A('ad-creative-drafts-never-go-live', 'Draft Ad Variants Into a Folder, Never Upload to the Ad Account',
          'grok bot ad creative', 'Tutorial', 'jobs', 2,
          'ad-creative-generator. Distinct from paid-media (spend watch) and competitor-ad-watch.',
          'grok-bot-paid-media,competitor-ad-watch-never-launches-ads'),
        A('enablement-pack-never-emails-the-rep', 'Build a Sales Enablement Pack the Rep Still Sends',
          'grok bot sales enablement', 'Tutorial', 'jobs', 2,
          'enablement-pack-builder. Distinct from sales-outbound and qbr-pack.',
          'grok-bot-sales-outbound,how-to-automate-qbr-prep'),
        A('qbr-pack-stays-a-draft', 'Assemble a QBR Deck Pack and Never Present It',
          'grok bot qbr pack', 'Tutorial', 'jobs', 2,
          'qbr-pack-builder. Distinct from how-to-automate-qbr-prep (process) and executive-briefing.',
          'how-to-automate-qbr-prep,grok-bot-executive-briefing'),
        A('win-loss-memo-never-closes-the-crm', 'Write a Win-Loss Memo From Notes You Saved, Never Stamp the Deal',
          'grok bot win loss memo', 'Tutorial', 'jobs', 2,
          'win-loss-memo. Distinct from how-to-automate-win-loss-analysis.',
          'how-to-automate-win-loss-analysis'),
        A('forecast-notes-never-change-the-number', 'Update Forecast Notes, Never Edit the Forecast Figure',
          'grok bot forecast notes', 'Tutorial', 'jobs', 2,
          'forecast-notes-updater. Distinct from how-to-automate-forecast-hygiene.',
          'how-to-automate-forecast-hygiene'),
        A('salesforce-report-export-never-shares', 'Build a Salesforce Report Spec, Never Share It Org-Wide',
          'grok bot salesforce report', 'Tutorial', 'jobs', 3,
          'salesforce-report-builder. Distinct from crm-hygiene (patch list) and for-revops.',
          'grok-bot-crm-hygiene,grok-bot-for-revops'),
        A('deal-desk-autopilot-never-discounts', 'Draft Deal-Desk Options, Never Apply a Discount in the CRM',
          'grok bot deal desk', 'Tutorial', 'jobs', 2,
          'deal-desk-autopilot. Distinct from how-to-automate-deal-desk.',
          'how-to-automate-deal-desk'),
        A('trust-center-answers-never-send-the-packet', 'Fill a Trust-Center Questionnaire Draft, Never Email the Buyer',
          'grok bot trust center', 'Tutorial', 'jobs', 2,
          'trust-center-deal-desk. Distinct from how-to-answer-security-questionnaires and prove-to-risk-committee.',
          'how-to-answer-security-questionnaires,prove-grok-bot-to-a-risk-committee'),
        A('prospect-meeting-booker-never-sends-the-invite', 'Propose Meeting Slots, Never Send the Calendar Invite',
          'grok bot book prospect meeting', 'Tutorial', 'jobs', 2,
          'prospect-meeting-booker. Distinct from calendar-manager (internal holds) and meeting-prep.',
          'grok-bot-calendar-manager,grok-bot-to-meeting-prep'),
        A('prospecting-sheet-from-public-pages', 'Fill a Prospect Sheet From Pages You Already Saved',
          'grok bot prospecting sheet', 'Tutorial', 'jobs', 3,
          'prospecting-sheet-builder. Distinct from how-to-build-a-prospect-research-sheet and lead-scout.',
          'how-to-build-a-prospect-research-sheet'),
        A('outbound-in-your-voice-still-never-sends', 'Draft Outbound in a Saved Voice Sample, Still Never Send',
          'grok bot outbound voice', 'Tutorial', 'jobs', 2,
          'outbound-in-your-voice. Distinct from grok-bot-sales-outbound (first-touch research).',
          'grok-bot-sales-outbound'),
        A('call-follow-up-drafter-human-sends', 'Draft the Call Follow-Up From the Transcript You Saved',
          'grok bot call follow up draft', 'Tutorial', 'jobs', 2,
          'call-follow-up-drafter. Distinct from how-to-automate-call-follow-ups and to-sales-followup.',
          'how-to-automate-call-follow-ups,grok-bot-to-sales-followup'),
        A('call-coach-never-joins-the-call', 'Score a Call Recording You Uploaded, Never Join Live Audio',
          'grok bot call coaching', 'Tutorial', 'jobs', 2,
          'call-coach. Distinct from how-to-coach-sales-calls-with-ai. Teach-by-demo is browser only, no mic.',
          'how-to-coach-sales-calls-with-ai'),
        A('meeting-double-never-accepts', 'Prep a Meeting Double Pack, Never Accept the Invite',
          'grok bot meeting double', 'Tutorial', 'jobs', 3,
          'meeting-double. Distinct from to-meeting-prep and calendar-manager.',
          'grok-bot-to-meeting-prep'),
        A('meeting-prep-brief-from-a-folder', 'Build Meeting Prep From a Closed Folder, Not From Live Mail Send',
          'grok bot meeting brief folder', 'Tutorial', 'jobs', 3,
          'meeting-prep-brief. Distinct from to-meeting-prep (job) and how-to-automate-meeting-prep.',
          'grok-bot-to-meeting-prep'),
        A('deck-updater-never-presents', 'Patch a Sales Deck From a Changelog, Never Present It',
          'grok bot update sales deck', 'Tutorial', 'jobs', 2,
          'deck-updater. Distinct from how-to-keep-sales-decks-current.',
          'how-to-keep-sales-decks-current'),
        A('deck-localizer-never-sends-the-local-file', 'Localize a Deck Into a Folder, Never Email the Affiliate',
          'grok bot localize deck', 'Tutorial', 'jobs', 3,
          'deck-localizer. Distinct from deck-updater.',
          'deck-updater-never-presents'),
        A('brand-deck-keeper-never-edits-figma-live', 'Diff Brand Rules Against a Deck Export, Never Edit Live Figma',
          'grok bot brand deck', 'Tutorial', 'jobs', 3,
          'brand-deck-keeper. Distinct from grok-bot-for-designers-figma-motion and bots-and-figma (held).',
          'grok-bot-for-designers-figma-motion'),
        A('org-chart-keeper-never-writes-hris', 'Keep an Org Chart File Current, Never Write the HRIS',
          'grok bot org chart file', 'Tutorial', 'jobs', 3,
          'org-chart-keeper. Distinct from how-to-maintain-an-org-chart.',
          'how-to-maintain-an-org-chart'),
        A('account-tiering-pack-never-changes-owner', 'Propose Account Tiers, Never Rewrite CRM Ownership',
          'grok bot account tiering pack', 'Tutorial', 'jobs', 2,
          'account-tiering. Distinct from how-to-automate-account-tiering and account-health.',
          'how-to-automate-account-tiering,grok-bot-account-health'),
        A('account-expert-internal-brief', 'Become the Internal Expert on One Account, Never Email Them',
          'grok bot account expert', 'Playbook', 'jobs', 2,
          'account-expert. Distinct from account-health (color pack) and for-customer-success (role).',
          'grok-bot-account-health,grok-bot-for-customer-success'),
        A('account-growth-planner-never-pitches', 'Plan Account Growth Moves as a Memo, Never Pitch Them',
          'grok bot account growth plan', 'Playbook', 'jobs', 3,
          'account-growth-planner. Distinct from account-expert and churn-watch.',
          'account-expert-internal-brief'),
        A('account-growth-coach-never-joins-the-qbr', 'Coach the AE From a Pack, Never Join the Customer Call',
          'grok bot account growth coach', 'Playbook', 'jobs', 3,
          'account-growth-coach. Distinct from growth-planner.',
          'account-growth-planner-never-pitches'),
        A('account-media-rundown-never-posts', 'Rundown Account Media Mentions, Never Reply in Public',
          'grok bot account media', 'Tutorial', 'jobs', 3,
          'account-media-rundown. Distinct from community-manager (never post) and viral-tweet-scout.',
          'grok-bot-community-manager'),
        A('churn-early-warning-still-no-customer-mail', 'Early Churn Signals as an Internal Note, Still No Customer Mail',
          'grok bot churn early warning', 'Tutorial', 'jobs', 2,
          'churn-early-warning. Distinct from to-churn-watch (save motion) and account-health.',
          'grok-bot-to-churn-watch,grok-bot-account-health'),
        A('churn-win-back-loop-draft-only', 'Draft a Win-Back Sequence, Never Send the First Step',
          'grok bot win back draft', 'Tutorial', 'jobs', 2,
          'churn-win-back-loop. Distinct from churn-watch and sales-outbound.',
          'grok-bot-to-churn-watch'),
        A('what-did-we-promise-log', 'Keep a Promise Log From Tickets and Calls, Never Close the Ticket',
          'grok bot promise log', 'Tutorial', 'jobs', 2,
          'what-did-we-promise. Distinct from how-to-track-customer-promises.',
          'how-to-track-customer-promises'),
        A('support-reply-drafter-agent-sends', 'Draft the Support Reply, the Agent Still Hits Send',
          'grok bot support reply draft', 'Tutorial', 'jobs', 2,
          'support-reply-drafter. Distinct from to-support-triage and cannot-send-email.',
          'grok-bot-to-support-triage,grok-bot-cannot-send-email'),
        A('support-queue-pass-never-assigns', 'Propose a Queue Pass Order, Never Assign the Ticket',
          'grok bot support queue', 'Tutorial', 'jobs', 3,
          'support-queue-pass. Distinct from support-triage and support-autopilot.',
          'grok-bot-to-support-triage'),
        A('support-autopilot-still-has-a-boundary', 'Name What Support Autopilot Must Never Close',
          'grok bot support autopilot', 'Safety', 'jobs', 2,
          'support-autopilot. Distinct from to-support-triage. Closing a ticket is irreversible.',
          'grok-bot-to-support-triage'),
        A('support-ticket-fixer-never-deploys', 'Propose a Ticket Fix as Steps, Never Deploy It',
          'grok bot support ticket fix', 'Tutorial', 'jobs', 3,
          'support-ticket-fixer. Distinct from bug-reproduction (screenshots) and product-investigation.',
          'grok-bot-bug-reproduction,what-is-actually-broken-behind-a-ticket'),
        A('help-center-updater-never-publishes-the-article', 'Draft a Help Center Diff, Never Publish the Article',
          'grok bot help center draft', 'Tutorial', 'jobs', 2,
          'help-center-updater. Distinct from how-to-automate-help-center-updates.',
          'how-to-automate-help-center-updates'),
        A('docs-self-serve-assistant-never-opens-a-ticket', 'Answer From the Help Center Export, Never File a Ticket',
          'grok bot docs assistant', 'Tutorial', 'jobs', 3,
          'docs-self-serve-assistant. Distinct from help-center-updater and support-triage.',
          'help-center-updater-never-publishes-the-article'),
        A('tickets-to-changelog-never-ships-the-note', 'Turn Tickets Into a Changelog Draft, Never Ship It',
          'grok bot changelog from tickets', 'Tutorial', 'jobs', 2,
          'tickets-to-changelog. Distinct from how-to-automate-changelog-writing.',
          'how-to-automate-changelog-writing'),
        A('inbox-reply-digest-never-replies', 'Digest Replies You Owe, Never Send Them',
          'grok bot inbox reply digest', 'Tutorial', 'jobs', 2,
          'inbox-reply-digest. Distinct from to-inbox-triage and cannot-send-email.',
          'grok-bot-to-inbox-triage'),
        A('email-purger-never-empties-trash', 'Propose Mail to Purge, Never Empty Trash Unattended',
          'grok bot email purge', 'Safety', 'jobs', 2,
          'email-purger. Distinct from mail-cleanup-assistant listing and inbox-triage.',
          'grok-bot-to-inbox-triage'),
        A('email-injection-sentinel-read-only', 'Flag Prompt Injection in Mail You Saved, Never Click the Link',
          'grok bot email prompt injection', 'Safety', 'jobs', 1,
          'email-injection-sentinel. Distinct from prompt-injection-for-operators if it exists, else browser-broke.',
          'grok-bot-browser-broke'),
        A('pr-review-sentinel-never-merges', 'Comment on a PR Diff You Exported, Never Merge',
          'grok bot pr review sentinel', 'Tutorial', 'jobs', 2,
          'pr-review-sentinel. Distinct from to-pr-review and vs-cursor-background-agent. Bot does not read SKILL.md.',
          'grok-bot-to-pr-review,grok-bot-vs-cursor-background-agent'),
        A('codebase-hardening-audit-never-patches-prod', 'Audit a Repo Export for Hardening Notes, Never Patch Prod',
          'grok bot codebase audit', 'Safety', 'jobs', 2,
          'codebase-hardening-auditor. Distinct from for-security-teams (alert CSV) and bug-reproduction.',
          'grok-bot-for-security-teams'),
        A('engineering-agent-manager-never-approves-the-pr', 'Track Engineering Agent Jobs, Never Approve Their PR',
          'grok bot engineering agent manager', 'Playbook', 'jobs', 3,
          'engineering-agent-manager. Distinct from vs-cursor-background-agent and vs-devin.',
          'grok-bot-vs-cursor-background-agent,grok-bot-vs-devin'),
        A('stuck-bot-foreman-never-retries-the-send', 'Foreman a Stuck Job: Inspect, Pause, Never Retry a Send',
          'grok bot stuck foreman', 'Guide', 'ops', 2,
          'stuck-bot-foreman. Distinct from grok-bot-stalled (restart protocol) and runbook.',
          'grok-bot-stalled,grok-bot-runbook'),
        A('vm-overwatch-cannot-see-your-laptop', 'Watch the Cloud Computer Health You Can See, Not Your Laptop',
          'grok bot vm overwatch', 'Reference', 'ops', 3,
          'vm-overwatch. Distinct from cannot-see-files and runs-with-laptop-closed. No invented CPU numbers.',
          'grok-bot-cannot-see-files,grok-bot-runs-with-laptop-closed'),
        A('persistent-memory-file-is-not-a-vault', 'A Memory File on the Shared Computer Is Visible to Every Bot',
          'grok bot persistent memory', 'Safety', 'architecture', 1,
          'persistent-bot-memory. Distinct from not-a-sandbox and one-computer-many-screens.',
          'grok-bot-not-a-sandbox,grok-bot-one-computer-many-screens'),
        A('firstmate-router-never-does-the-job', 'Route the Request to a Named Bot, Never Do the Job Yourself',
          'grok bot firstmate router', 'Playbook', 'jobs', 3,
          'firstmate-router. Distinct from route-work-through-one-bot (chief-of-staff-router).',
          'route-work-through-one-bot'),
        A('fleet-chief-of-staff-still-one-computer', 'A Fleet Chief of Staff Still Shares One Computer Per Account',
          'grok bot fleet chief of staff', 'Playbook', 'jobs', 2,
          'fleet-chief-of-staff. Distinct from executive-briefing and agencies-isolation.',
          'grok-bot-executive-briefing,grok-bot-for-agencies-isolation'),
        A('telegram-fleet-door-never-runs-commands', 'Use Telegram as a Door, Never as a Place to Paste Secrets',
          'grok bot telegram', 'Safety', 'architecture', 2,
          'telegram-fleet-door. Distinct from share-a-grok-bot (no share button) and iphone-cannot-edit.',
          'share-a-grok-bot,grok-bot-iphone-cannot-edit'),
        A('agent-inbox-is-not-gmail-send', 'Treat Agent Inbox as a Queue of Drafts, Not a Send Grant',
          'grok bot agent inbox', 'Guide', 'jobs', 2,
          'agent-inbox. Distinct from to-inbox-triage and how-to-connect-gmail.',
          'grok-bot-to-inbox-triage,how-to-connect-gmail-to-grok-bot'),
        A('bot-advisor-never-creates-the-bot', 'Advise Which Listing to Paste, Never Create the Bot for Them',
          'grok bot advisor', 'Guide', 'getting-started', 3,
          'bot-advisor. Distinct from read-a-grok-bot-listing and pick-the-first-grok-bot-job.',
          'read-a-grok-bot-listing,pick-the-first-grok-bot-job'),
        A('product-expert-from-a-closed-corpus', 'Answer Product Questions From a Closed Corpus, Never From Vibes',
          'grok bot product expert', 'Tutorial', 'jobs', 2,
          'product-expert. Distinct from product-investigation (conversion mystery).',
          'grok-bot-product-investigation,grok-bot-evidence-rules'),
        A('evergreen-content-flywheel-never-auto-posts', 'Refresh Evergreen Drafts, Never Auto-Post Them',
          'grok bot evergreen content', 'Tutorial', 'jobs', 3,
          'evergreen-content-flywheel. Distinct from content-calendar and content-ideas.',
          'grok-bot-to-content-calendar,content-ideas-that-never-become-posts'),
        A('directory-page-drafter-never-publishes-the-url', 'Draft a Directory Page, Never Publish the URL',
          'grok bot directory page', 'Tutorial', 'jobs', 3,
          'directory-page-drafter. Distinct from grok-bot-directory-business (research a page a day).',
          'grok-bot-directory-business'),
        A('motivated-seller-finder-never-calls-them', 'Flag Public Seller Signals, Never Call or Text the Owner',
          'grok bot motivated seller', 'Tutorial', 'jobs', 2,
          'motivated-seller-finder. Distinct from bots-for-real-estate and bargain-scout.',
          'bots-for-real-estate,watch-listings-without-bidding'),
        A('booking-pipeline-never-charges-the-card', 'Move a Booking Pipeline Row, Never Charge the Card',
          'grok bot booking pipeline', 'Tutorial', 'jobs', 2,
          'booking-pipeline-runner. Distinct from calendar-manager and stayingapi-compare.',
          'grok-bot-calendar-manager,grok-bot-stayingapi-compare'),
        A('bookkeeping-auditor-never-posts-the-journal', 'Flag Bookkeeping Exceptions, Never Post a Journal Entry',
          'grok bot bookkeeping audit', 'Tutorial', 'jobs', 2,
          'bookkeeping-auditor. Distinct from for-accountants and expense-manager.',
          'grok-bot-for-accountants,grok-bot-expense-manager'),
        A('sponsor-inbound-scout-never-replies', 'Score Inbound Sponsor Mail, Never Reply',
          'grok bot sponsor inbound', 'Tutorial', 'jobs', 2,
          'sponsor-inbound-scout. Distinct from sponsorship-inbox-score and sponsorship-negotiator.',
          'grok-bot-sponsorship-inbox-score,counter-from-your-own-rate-history'),

        # --- integrations (hedge vendor pages, unique never-line) ---
        A('bots-and-hubspot', 'Bots and HubSpot: Patch Lists, Never Ownership Writes',
          'grok bot hubspot', 'Guide', 'integrations', 1,
          'No HubSpot article. Distinct from crm-hygiene (generic CRM) and composio (vendor hedge).',
          'grok-bot-crm-hygiene,grok-bot-composio'),
        A('bots-and-salesforce', 'Bots and Salesforce: Exports First, Console Login Last',
          'grok bot salesforce', 'Guide', 'integrations', 1,
          'Distinct from salesforce-report-export and for-revops.',
          'salesforce-report-export-never-shares,grok-bot-for-revops'),
        A('bots-and-stripe', 'Bots and Stripe: Read Payouts, Never Refund or Capture',
          'grok bot stripe', 'Safety', 'integrations', 1,
          'Refund and capture are irreversible. Distinct from expense-manager.',
          'grok-bot-expense-manager'),
        A('bots-and-quickbooks', 'Bots and QuickBooks: Reconcile Exports, Never File',
          'grok bot quickbooks', 'Guide', 'integrations', 2,
          'Distinct from for-accountants (role) and bookkeeping-auditor.',
          'grok-bot-for-accountants'),
        A('bots-and-xero', 'Bots and Xero: Exception Lists, Never Submit GST',
          'grok bot xero', 'Guide', 'integrations', 3,
          'Distinct from quickbooks and for-accountants. Hedge Xero features.',
          'bots-and-quickbooks'),
        A('bots-and-notion', 'Bots and Notion: Draft Pages in a Private DB, Never Share to Web',
          'grok bot notion', 'Guide', 'integrations', 2,
          'Distinct from grok-bot-obsidian-knowledge-base if live, else to-doc-cleanup.',
          'grok-bot-to-doc-cleanup'),
        A('bots-and-linear', 'Bots and Linear: Draft Issues, Never Close or Assign',
          'grok bot linear', 'Guide', 'integrations', 2,
          'Distinct from to-bug-triage and to-pr-review.',
          'grok-bot-to-bug-triage'),
        A('bots-and-github', 'Bots and GitHub: Comment Drafts, Never Merge, Never Write Secrets',
          'grok bot github', 'Safety', 'integrations', 1,
          'Distinct from to-pr-review and vs-cursor-background-agent. SKILL.md is Grok Build.',
          'grok-bot-to-pr-review,grok-bot-vs-grok-build'),
        A('bots-and-gitlab', 'Bots and GitLab: Same Merge Freeze as GitHub',
          'grok bot gitlab', 'Safety', 'integrations', 3,
          'Distinct from bots-and-github. Hedge GitLab.',
          'bots-and-github'),
        A('bots-and-slack', 'Bots and Slack: Private Drafts, Never Post in a Public Channel',
          'grok bot slack', 'Safety', 'integrations', 1,
          'Distinct from community-manager (Discord/forum) and group-chat.',
          'grok-bot-community-manager,grok-bot-group-chat'),
        A('bots-and-microsoft-teams', 'Bots and Microsoft Teams: Draft in a Doc, Never Send the Channel',
          'grok bot microsoft teams', 'Guide', 'integrations', 2,
          'Distinct from vs-microsoft-copilot and bots-and-slack.',
          'grok-bot-vs-microsoft-copilot,bots-and-slack'),
        A('bots-and-discord', 'Bots and Discord: Export Threads, Never Sit on the Admin Login',
          'grok bot discord', 'Safety', 'integrations', 2,
          'Distinct from community-manager. Cookie jar warning.',
          'grok-bot-community-manager,grok-bot-2fa-prompt'),
        A('bots-and-telegram', 'Bots and Telegram: A Door Is Not a Secret Store',
          'grok bot telegram integration', 'Safety', 'integrations', 3,
          'Distinct from telegram-fleet-door (catalog). Hedge Telegram bots API.',
          'telegram-fleet-door-never-runs-commands'),
        A('bots-and-calendly', 'Bots and Calendly: Propose Times, Never Publish a New Event Type',
          'grok bot calendly', 'Guide', 'integrations', 2,
          'From plan-100-v2 leftover. Distinct from calendar-manager.',
          'grok-bot-calendar-manager,prospect-meeting-booker-never-sends-the-invite'),
        A('bots-and-mailchimp', 'Bots and Mailchimp: Draft a Campaign, Never Hit Send',
          'grok bot mailchimp', 'Safety', 'integrations', 2,
          'From plan-100-v2. Distinct from to-newsletter-digest.',
          'grok-bot-to-newsletter-digest'),
        A('bots-and-shopify', 'Bots and Shopify: Read Orders, Never Capture or Refund',
          'grok bot shopify', 'Safety', 'integrations', 1,
          'Agency leak path already in agencies-isolation. This is the merchant job.',
          'grok-bot-for-agencies-isolation,bots-and-stripe'),
        A('bots-and-woocommerce', 'Bots and WooCommerce: Export First, Admin Login Last',
          'grok bot woocommerce', 'Guide', 'integrations', 3,
          'Distinct from shopify. Hedge Woo.',
          'bots-and-shopify'),
        A('bots-and-airtable', 'Bots and Airtable: Propose Rows, Never Bulk-Overwrite',
          'grok bot airtable', 'Guide', 'integrations', 2,
          'Distinct from crm-hygiene. Bulk overwrite is irreversible enough.',
          'grok-bot-crm-hygiene'),
        A('bots-and-google-sheets', 'Bots and Google Sheets: A Sheet Is Shared-Computer Visible',
          'grok bot google sheets', 'Safety', 'integrations', 2,
          'Distinct from cannot-see-files (path) and evidence-rules.',
          'grok-bot-cannot-see-files'),
        A('bots-and-excel', 'Bots and Excel Workbooks You Dropped in /workspace',
          'grok bot excel', 'Guide', 'integrations', 3,
          'Laptop Desktop.xlsx is invisible. Distinct from google-sheets.',
          'bots-and-google-sheets,grok-bot-cannot-see-files'),
        A('bots-and-intercom', 'Bots and Intercom: Draft Replies, Never Close the Conversation',
          'grok bot intercom', 'Guide', 'integrations', 2,
          'Distinct from support-reply-drafter and to-support-triage.',
          'support-reply-drafter-agent-sends'),
        A('bots-and-freshdesk', 'Bots and Freshdesk: Same Close Freeze as Intercom',
          'grok bot freshdesk', 'Guide', 'integrations', 3,
          'Distinct from intercom and zendesk (live).',
          'bots-and-intercom,bots-and-zendesk'),
        A('bots-and-zoom', 'Bots and Zoom: Recap a Recording You Own, Never Start the Meeting',
          'grok bot zoom recap', 'Guide', 'integrations', 2,
          'Distinct from meeting-prep and call-coach. Hedge Zoom AI.',
          'call-coach-never-joins-the-call'),
        A('bots-and-loom', 'Bots and Loom: Index Recordings You Saved, Never Share Publicly',
          'grok bot loom', 'Guide', 'integrations', 3,
          'Distinct from demo-clip-library (plan-50) and zoom.',
          'find-the-clip-that-answers-the-objection'),
        A('bots-and-canva', 'Bots and Canva: Brief the Design, Never Publish the Brand Kit',
          'grok bot canva', 'Guide', 'integrations', 3,
          'Distinct from ad-creative-drafts and brand-deck-keeper.',
          'ad-creative-drafts-never-go-live'),
        A('bots-and-wordpress', 'Bots and WordPress: Draft in a Staging Export, Never Hit Publish',
          'grok bot wordpress', 'Safety', 'integrations', 2,
          'Distinct from bots-and-webflow (plan-50).',
          'bots-and-webflow'),
        A('bots-and-ghost', 'Bots and Ghost: Same Publish Freeze as WordPress',
          'grok bot ghost cms', 'Guide', 'integrations', 3,
          'Distinct from wordpress and webflow.',
          'bots-and-wordpress'),
        A('bots-and-substack', 'Bots and Substack: Draft the Issue, Never Send to the List',
          'grok bot substack', 'Safety', 'integrations', 2,
          'Distinct from mailchimp and newsletter-digest.',
          'bots-and-mailchimp,grok-bot-to-newsletter-digest'),
        A('bots-and-beehiiv', 'Bots and Beehiiv: Draft, Never Send',
          'grok bot beehiiv', 'Guide', 'integrations', 3,
          'Distinct from substack. Hedge Beehiiv.',
          'bots-and-substack'),
        A('bots-and-typeform', 'Bots and Typeform: Summarize Responses, Never Edit a Live Form',
          'grok bot typeform', 'Guide', 'integrations', 3,
          'Editing a live form is customer-facing.',
          'grok-bot-evidence-rules'),
        A('bots-and-pagerduty', 'Bots and PagerDuty: Cluster Alerts You Exported, Never Ack Prod',
          'grok bot pagerduty', 'Safety', 'integrations', 2,
          'Distinct from for-security-teams and on-call.',
          'grok-bot-for-security-teams,grok-bot-on-call'),
        A('bots-and-datadog', 'Bots and Datadog: Read an Export, Never Mute a Monitor',
          'grok bot datadog', 'Safety', 'integrations', 3,
          'Muting is production. Distinct from pagerduty.',
          'bots-and-pagerduty'),
        A('bots-and-sentry', 'Bots and Sentry: Group Errors From an Export, Never Resolve',
          'grok bot sentry', 'Guide', 'integrations', 3,
          'Distinct from bug-reproduction and product-investigation.',
          'grok-bot-bug-reproduction'),
        A('bots-and-okta', 'Bots and Okta: Never Sit on the Admin Console Cookie',
          'grok bot okta', 'Safety', 'integrations', 1,
          'SSO admin is a house key. Distinct from isolate-credentials and 2fa-prompt.',
          'how-to-isolate-grok-bot-credentials,grok-bot-2fa-prompt'),
        A('bots-and-1password', 'Bots and 1Password: Never Paste the Vault onto the Shared Computer',
          'grok bot 1password', 'Safety', 'integrations', 1,
          'Password managers on the shared computer are a blast radius. Distinct from isolate-credentials.',
          'how-to-isolate-grok-bot-credentials,grok-bot-not-a-sandbox'),
        A('bots-and-jira-cloud', 'Bots and Jira Cloud: Draft Tickets, Never Transition Done',
          'grok bot jira', 'Guide', 'integrations', 2,
          'Distinct from bots-and-jira-service-management (live ITSM) and to-bug-triage.',
          'bots-and-jira-service-management,grok-bot-to-bug-triage'),
        A('bots-and-confluence', 'Bots and Confluence: Draft a Page, Never Make It Global',
          'grok bot confluence', 'Guide', 'integrations', 3,
          'Distinct from notion and to-doc-cleanup.',
          'bots-and-notion'),
        A('bots-and-looker', 'Bots and Looker: Quote a Dashboard Export, Never Change a Tile',
          'grok bot looker', 'Guide', 'integrations', 3,
          'Distinct from to-kpi-reporting.',
          'grok-bot-to-kpi-reporting,grok-bot-evidence-rules'),
        A('bots-and-tableau', 'Bots and Tableau: Same Quote Rule as Looker',
          'grok bot tableau', 'Guide', 'integrations', 3,
          'Distinct from looker and kpi-reporting.',
          'bots-and-looker'),
        A('bots-and-mixpanel-exports', 'Mixpanel Exports Are Safer Than a Shared Console Cookie',
          'grok bot mixpanel export', 'Guide', 'integrations', 3,
          'bots-and-mixpanel is held as a clone. This page is export-vs-console only.',
          'grok-bot-product-investigation'),
        A('bots-and-segment', 'Bots and Segment: Never Edit a Live Source',
          'grok bot segment', 'Safety', 'integrations', 3,
          'Live source edits affect production data.',
          'bots-and-mixpanel-exports'),
        A('bots-and-twilio', 'Bots and Twilio: Never Send the SMS, Even as a Test',
          'grok bot twilio', 'Safety', 'integrations', 2,
          'SMS is a send. Distinct from whatsapp (plan-50).',
          'bots-and-whatsapp'),
        A('bots-and-sendgrid', 'Bots and SendGrid: Never Fire the Campaign',
          'grok bot sendgrid', 'Safety', 'integrations', 3,
          'Distinct from mailchimp and cannot-send-email.',
          'bots-and-mailchimp,grok-bot-cannot-send-email'),

        # --- comparisons (hedge every vendor) ---
        A('grok-bot-vs-copilot-studio', 'Grok Bot vs Copilot Studio: Named Teammate vs Tenant Agent',
          'grok bot vs copilot studio', 'Comparison', 'comparisons', 2,
          'Distinct from vs-microsoft-copilot (M365 help). Hedge Copilot Studio.',
          'grok-bot-vs-microsoft-copilot'),
        A('grok-bot-vs-gemini-workspace-agents', 'Grok Bot vs Gemini Workspace Agents: Two Clouds, Two Cookie Jars',
          'grok bot vs gemini agents', 'Comparison', 'comparisons', 2,
          'Distinct from vs-gemini-gems (named helpers inside Gemini). Hedge Google.',
          'grok-bot-vs-gemini-gems'),
        A('grok-bot-vs-salesforce-agentforce', 'Grok Bot vs Agentforce: Teammate Computer vs CRM-Native Agent',
          'grok bot vs agentforce', 'Comparison', 'comparisons', 2,
          'Hedge Salesforce. Distinct from bots-and-salesforce.',
          'bots-and-salesforce,grok-bot-for-revops'),
        A('grok-bot-vs-hubspot-breeze', 'Grok Bot vs HubSpot Breeze: Confirm Breeze Live, Persistence Is Ours',
          'grok bot vs hubspot breeze', 'Comparison', 'comparisons', 3,
          'Hedge HubSpot. Distinct from bots-and-hubspot.',
          'bots-and-hubspot'),
        A('grok-bot-vs-intercom-fin', 'Grok Bot vs Intercom Fin: Draft Desk vs a Support Agent You Confirm',
          'grok bot vs intercom fin', 'Comparison', 'comparisons', 2,
          'Hedge Intercom Fin. Distinct from bots-and-intercom and to-support-triage.',
          'bots-and-intercom,grok-bot-to-support-triage'),
        A('grok-bot-vs-sierra', 'Grok Bot vs Sierra: Confirm Sierra Live, Our Send Freeze Stays',
          'grok bot vs sierra', 'Comparison', 'comparisons', 3,
          'Hedge Sierra. Distinct from vs-intercom-fin.',
          'grok-bot-vs-intercom-fin'),
        A('grok-bot-vs-decagon', 'Grok Bot vs Decagon: Confirm Decagon Live',
          'grok bot vs decagon', 'Comparison', 'comparisons', 3,
          'Hedge Decagon. Distinct from vs-sierra.',
          'grok-bot-vs-sierra'),
        A('grok-bot-vs-bardeen', 'Grok Bot vs Bardeen: Persistent Computer vs a Browser Automation You Confirm',
          'grok bot vs bardeen', 'Comparison', 'comparisons', 3,
          'Hedge Bardeen. Distinct from vs-computer-use and vs-zapier.',
          'grok-bot-vs-computer-use,grok-bot-vs-zapier'),
        A('grok-bot-vs-gumloop', 'Grok Bot vs Gumloop: Named Bot vs a Workflow Canvas You Confirm',
          'grok bot vs gumloop', 'Comparison', 'comparisons', 3,
          'Hedge Gumloop. Distinct from vs-lindy and ai-agents-vs-workflow-builders.',
          'grok-bot-vs-lindy,ai-agents-vs-workflow-builders'),
        A('grok-bot-vs-relay', 'Grok Bot vs Relay.app: Confirm Relay Live',
          'grok bot vs relay app', 'Comparison', 'comparisons', 3,
          'Hedge Relay. Distinct from gumloop and lindy.',
          'grok-bot-vs-gumloop'),
        A('grok-bot-vs-relevance-ai', 'Grok Bot vs Relevance AI: Confirm Relevance Live',
          'grok bot vs relevance ai', 'Comparison', 'comparisons', 3,
          'Hedge Relevance. Distinct from vs-lindy.',
          'grok-bot-vs-lindy'),
        A('grok-bot-vs-crewai', 'Grok Bot vs CrewAI: A Hosted Teammate vs a Framework You Run',
          'grok bot vs crewai', 'Comparison', 'comparisons', 2,
          'Hedge CrewAI. Distinct from build-vs-buy and vs-openclaw.',
          'build-vs-buy-ai-agents,grok-bot-vs-openclaw-vs-hermes-vs-buzz'),
        A('grok-bot-vs-langgraph', 'Grok Bot vs LangGraph: Product vs Graph You Maintain',
          'grok bot vs langgraph', 'Comparison', 'comparisons', 3,
          'Hedge LangGraph. Distinct from vs-crewai.',
          'grok-bot-vs-crewai'),
        A('grok-bot-vs-autogen', 'Grok Bot vs AutoGen: Confirm Microsoft AutoGen Live',
          'grok bot vs autogen', 'Comparison', 'comparisons', 3,
          'Hedge AutoGen. Distinct from vs-crewai.',
          'grok-bot-vs-crewai'),
        A('grok-bot-vs-replit-agent', 'Grok Bot vs Replit Agent: Ops Teammate vs a Coding Workspace You Confirm',
          'grok bot vs replit agent', 'Comparison', 'comparisons', 2,
          'Hedge Replit. Distinct from vs-devin and vs-cursor-background-agent. SKILL.md is Build.',
          'grok-bot-vs-devin,grok-bot-vs-cursor-background-agent'),
        A('grok-bot-vs-claude-code', 'Grok Bot vs Claude Code: Wrong Surface, That Is Grok Build',
          'grok bot vs claude code', 'Comparison', 'comparisons', 1,
          'The mix-up. Grok Bot docs never mention SKILL.md. Distinct from vs-grok-build.',
          'grok-bot-vs-grok-build'),
        A('grok-bot-vs-cursor-bugbot', 'Grok Bot vs Cursor Bugbot: Mail Teammate vs a PR Reviewer You Confirm',
          'grok bot vs bugbot', 'Comparison', 'comparisons', 2,
          'Hedge Bugbot. Distinct from vs-cursor-background-agent (already hedged Cloud Agents).',
          'grok-bot-vs-cursor-background-agent'),
        A('grok-bot-vs-github-copilot-workspace', 'Grok Bot vs Copilot Workspace: Confirm GitHub Live',
          'grok bot vs copilot workspace', 'Comparison', 'comparisons', 3,
          'Hedge GitHub. Distinct from vs-copilot and vs-copilot-studio.',
          'grok-bot-vs-microsoft-copilot,grok-bot-vs-copilot-studio'),
        A('grok-bot-vs-amazon-q', 'Grok Bot vs Amazon Q: Confirm Amazon Live',
          'grok bot vs amazon q', 'Comparison', 'comparisons', 3,
          'Hedge Amazon Q. Distinct from vs-copilot.',
          'grok-bot-vs-microsoft-copilot'),
        A('grok-bot-vs-google-mariner', 'Grok Bot vs Project Mariner: Persistence vs a Browser Agent You Confirm',
          'grok bot vs mariner', 'Comparison', 'comparisons', 3,
          'Hedge Google Mariner. Distinct from vs-computer-use and vs-chatgpt-agent.',
          'grok-bot-vs-computer-use,grok-bot-vs-chatgpt-agent'),
        A('grok-bot-vs-browser-use', 'Grok Bot vs browser-use: A Product vs a Library You Host',
          'grok bot vs browser use', 'Comparison', 'comparisons', 3,
          'Hedge the library. Distinct from vs-computer-use.',
          'grok-bot-vs-computer-use,grok-bot-vs-crewai'),
        A('grok-bot-vs-skyvern', 'Grok Bot vs Skyvern: Confirm Skyvern Live',
          'grok bot vs skyvern', 'Comparison', 'comparisons', 3,
          'Hedge Skyvern. Distinct from browser-use.',
          'grok-bot-vs-browser-use'),
        A('grok-bot-vs-apple-intelligence', 'Grok Bot vs Apple Intelligence: Cloud Computer vs On-Device You Confirm',
          'grok bot vs apple intelligence', 'Comparison', 'comparisons', 3,
          'Hedge Apple. Distinct from iphone-app and iphone-cannot-edit.',
          'grok-bot-iphone-app,how-to-pause-a-grok-bot-on-iphone'),
        A('ai-agents-vs-rpa', 'Agents vs RPA: Persistence and a Cookie Jar vs a Script You Own',
          'ai agents vs rpa', 'Comparison', 'decision', 2,
          'From plan-100-v2 leftover. Distinct from vs-computer-use and vs-zapier.',
          'grok-bot-vs-computer-use,grok-bot-vs-zapier'),
        A('ai-agents-vs-hiring', 'A Bot Is Not a Headcount Line',
          'ai agents vs hiring', 'Comparison', 'decision', 2,
          'From plan-100-v2. Distinct from explain-to-boss and for-hr. No invented savings percents.',
          'explain-grok-bot-to-your-boss,grok-bot-for-hr'),
        A('hosted-vs-self-hosted-agents', 'Hosted Grok Bot vs Self-Hosted Agents: Who Owns the Computer',
          'hosted vs self hosted agents', 'Comparison', 'decision', 2,
          'From plan-100-v2. Distinct from vs-openclaw and build-vs-buy.',
          'build-vs-buy-ai-agents,grok-bot-vs-openclaw-vs-hermes-vs-buzz'),
        A('open-source-vs-commercial-agents', 'Open-Source Agents vs Grok Bot: You Still Own Isolation',
          'open source vs commercial agents', 'Comparison', 'decision', 3,
          'From plan-100-v2. Distinct from hosted-vs-self-hosted.',
          'hosted-vs-self-hosted-agents'),
        A('mcp-vs-connectors', 'MCP vs Connectors vs Browser Login: Where the Token Lives',
          'mcp vs connectors grok bot', 'Comparison', 'architecture', 1,
          'From plan-100-v2. Distinct from mcp-servers and hosted-mcp-tokens and composio.',
          'grok-bot-mcp-servers,grok-bot-hosted-mcp-tokens,grok-bot-composio'),
        A('agent-frameworks-compared', 'Agent Frameworks Compared Without Pretending Grok Bot Is One',
          'agent frameworks compared', 'Comparison', 'decision', 3,
          'From plan-100-v2. Distinct from vs-crewai and vs-langgraph.',
          'grok-bot-vs-crewai,grok-bot-vs-langgraph'),

        # --- roles not covered as grok-bot-for-X ---
        A('grok-bot-for-founders-week-one', 'Grok Bot for Founders: One Never-Send Job Before the Public Inbox',
          'grok bot for founders', 'Guide', 'roles', 1,
          'Distinct from bots-for-founders (catalog roster) and week-one-mistakes and pick-the-first.',
          'bots-for-founders,grok-bot-week-one-mistakes,pick-the-first-grok-bot-job'),
        A('grok-bot-for-solopreneurs', 'Grok Bot for Solopreneurs: One Computer, No VA, No Send',
          'grok bot for solopreneurs', 'Guide', 'roles', 2,
          'Distinct from one-person-company-grok-bot and replace-a-va-shift.',
          'one-person-company-grok-bot,replace-a-va-shift-with-a-grok-bot'),
        A('grok-bot-for-freelancers', 'Grok Bot for Freelancers: Client Files Stay Off the Shared Disk',
          'grok bot for freelancers', 'Safety', 'roles', 2,
          'Distinct from bots-for-freelancers leftover and agencies-isolation.',
          'grok-bot-for-agencies-isolation,how-to-isolate-grok-bot-credentials'),
        A('grok-bot-for-real-estate-agents', 'Grok Bot for Real Estate: Watch Listings, Never Message the Owner',
          'grok bot for real estate', 'Guide', 'roles', 2,
          'Distinct from bots-for-real-estate and motivated-seller-finder.',
          'bots-for-real-estate,motivated-seller-finder-never-calls-them'),
        A('grok-bot-for-ecommerce-ops', 'Grok Bot for Ecommerce Ops: Read Orders, Never Capture',
          'grok bot for ecommerce', 'Guide', 'roles', 2,
          'Distinct from bots-for-ecommerce and bots-and-shopify.',
          'bots-for-ecommerce,bots-and-shopify'),
        A('grok-bot-for-product-managers', 'Grok Bot for Product Managers: Investigation Packs, Never Ship',
          'grok bot for product managers', 'Guide', 'roles', 2,
          'Distinct from bots-for-product-managers and product-investigation.',
          'bots-for-product-managers,grok-bot-product-investigation'),
        A('grok-bot-for-engineers-ops-not-merge', 'Grok Bot for Engineers: Ops Teammate, Not a Merge Bot',
          'grok bot for engineers', 'Guide', 'roles', 1,
          'Distinct from bots-for-engineers, vs-devin, vs-grok-build.',
          'bots-for-engineers,grok-bot-vs-devin,grok-bot-vs-grok-build'),
        A('grok-bot-for-support-leads', 'Grok Bot for Support Leads: Drafts in a Label, Never Close',
          'grok bot for support leads', 'Guide', 'roles', 2,
          'Distinct from bots-for-support-leads and to-support-triage.',
          'bots-for-support-leads,grok-bot-to-support-triage'),
        A('grok-bot-for-marketers-never-publish', 'Grok Bot for Marketers: Calendars and Drafts, Never Publish',
          'grok bot for marketers', 'Guide', 'roles', 2,
          'Distinct from bots-for-marketers, paid-media, youtube-creators.',
          'bots-for-marketers,grok-bot-paid-media'),
        A('grok-bot-for-sales-managers', 'Grok Bot for Sales Managers: Forecast Notes, Never Rewrite Quota',
          'grok bot for sales managers', 'Guide', 'roles', 2,
          'Distinct from bots-for-sales-reps and sales-outbound.',
          'bots-for-sales-reps,grok-bot-sales-outbound'),
        A('grok-bot-for-data-teams', 'Grok Bot for Data Teams: Quote Exports, Never Change the Warehouse',
          'grok bot for data teams', 'Guide', 'roles', 3,
          'From plan-100-v2 leftover. Distinct from looker and kpi-reporting.',
          'bots-and-looker,grok-bot-to-kpi-reporting'),
        A('grok-bot-for-technical-writers', 'Grok Bot for Technical Writers: Diff Drafts, Never Publish Docs',
          'grok bot for technical writers', 'Guide', 'roles', 3,
          'From plan-100-v2. Distinct from help-center-updater and to-doc-cleanup.',
          'help-center-updater-never-publishes-the-article,grok-bot-to-doc-cleanup'),
        A('grok-bot-for-teachers-never-grades-live', 'Grok Bot for Teachers: Recap Materials You Own, Never Submit Grades',
          'grok bot for teachers', 'Guide', 'roles', 3,
          'Distinct from bots-for-teachers and for-students. Academic integrity.',
          'bots-for-teachers,grok-bot-for-students'),
        A('grok-bot-for-writers-never-posts', 'Grok Bot for Writers: Drafts in /workspace, Never Hit Publish',
          'grok bot for writers', 'Guide', 'roles', 3,
          'Distinct from bots-for-writers and youtube-creators.',
          'bots-for-writers'),
        A('grok-bot-for-consultants-client-isolation', 'Grok Bot for Consultants: One Eligible Account Per Client or No Console',
          'grok bot for consultants', 'Safety', 'roles', 2,
          'Distinct from bots-for-consultants and agencies-isolation.',
          'bots-for-consultants,grok-bot-for-agencies-isolation'),
        A('grok-bot-for-finance-teams-never-pay', 'Grok Bot for Finance Teams: Exception Lists, Never Pay',
          'grok bot for finance teams', 'Guide', 'roles', 2,
          'Distinct from bots-for-finance, for-accountants, personal-cfo.',
          'bots-for-finance,grok-bot-for-accountants,personal-cfo-brief-never-moves-money'),
        A('grok-bot-for-recruiters-never-inmail', 'Grok Bot for Recruiters: Score Saved Pages, Never InMail',
          'grok bot for recruiters', 'Guide', 'roles', 2,
          'Distinct from bots-for-recruiters, for-hr, talent-scout.',
          'bots-for-recruiters,grok-bot-for-hr,grok-bot-talent-scout'),
        A('grok-bot-for-customer-success-teams-roster', 'CS Teams: One Friday Bot Each, Not a Shared Seat',
          'grok bot for cs teams', 'Guide', 'roles', 3,
          'From plan-100-v2 bots-for-customer-success-teams leftover. Distinct from for-customer-success (role page).',
          'grok-bot-for-customer-success,grok-bot-teams-standard'),
        A('grok-bot-revops-across-seats', 'RevOps Across Seats: Patch Lists Per Person, Still No Ownership Writes',
          'grok bot revops across seats', 'Guide', 'roles', 3,
          'From plan-100-v2. Distinct from grok-bot-for-revops (already live). This is multi-seat ops, not the role page.',
          'grok-bot-for-revops,grok-bot-teams-standard'),

        # --- ops / safety / how-to leftover from plan-100-v2 ---
        A('bot-charter-anti-patterns', 'Charter Anti-Patterns: Be Helpful, and Other First-Week Failures',
          'bot charter anti patterns', 'Reference', 'ops', 1,
          'From plan-100-v2. Distinct from how-to-write-a-grok-bot-charter-2026 and week-one-mistakes.',
          'how-to-write-a-grok-bot-charter-2026,grok-bot-week-one-mistakes'),
        A('how-to-audit-a-bot-you-inherited', 'Audit a Bot You Inherited Before You Widen Its Grants',
          'audit inherited grok bot', 'Guide', 'ops', 1,
          'From plan-100-v2. Distinct from read-a-listing and retirement.',
          'read-a-grok-bot-listing,grok-bot-retirement'),
        A('bot-permission-review-checklist', 'A Permission Review You Can Fail, Not a Slogan',
          'bot permission review', 'Safety', 'ops', 2,
          'From plan-100-v2. Distinct from preflight-checklist and least-privilege-bots.',
          'grok-bot-preflight-checklist,least-privilege-bots'),
        A('prompt-injection-for-operators', 'Prompt Injection for Operators: The Page Can Instruct the Bot',
          'grok bot prompt injection', 'Safety', 'ops', 1,
          'From plan-100-v2 and topics-grok-100. Distinct from email-injection-sentinel (mail) and browser-broke.',
          'email-injection-sentinel-read-only,grok-bot-browser-broke'),
        A('bot-incident-response', 'Incident Response When a Bot Already Did the Thing',
          'grok bot incident response', 'Safety', 'ops', 1,
          'From plan-100-v2. Distinct from rotate-vendor-access and on-call. Approval is not undo.',
          'rotate-vendor-access-after-a-bad-grok-bot-incident,grok-bot-on-call'),
        A('how-to-sandbox-a-bot', 'You Cannot Sandbox a Grok Bot With Another Bot',
          'sandbox grok bot', 'Safety', 'ops', 1,
          'From plan-100-v2. Distinct from not-a-sandbox. Honest options: second eligible account or no secrets on disk.',
          'grok-bot-not-a-sandbox,how-to-isolate-grok-bot-credentials'),
        A('credential-hygiene-for-bots', 'Credential Hygiene: Rotate What the Computer Touched',
          'bot credential hygiene', 'Safety', 'ops', 2,
          'From plan-100-v2. Distinct from isolate-credentials (menu) and rotate-vendor-access (incident).',
          'how-to-isolate-grok-bot-credentials,rotate-vendor-access-after-a-bad-grok-bot-incident'),
        A('bot-output-verification', 'Verify Bot Output Before Anyone Repeats It',
          'verify grok bot output', 'Guide', 'ops', 2,
          'From plan-100-v2. Distinct from evidence-rules (charter block) and shadow-mode (scored week).',
          'grok-bot-evidence-rules,grok-bot-shadow-mode'),
        A('when-not-to-use-a-bot', 'When Not to Use a Grok Bot This Week',
          'when not to use grok bot', 'Guide', 'getting-started', 1,
          'From plan-100-v2. Distinct from pick-the-first and regulated-industries.',
          'pick-the-first-grok-bot-job,grok-bot-regulated-industries'),
        A('bot-handover-documentation', 'Handover Notes When the Owner Goes on PTO',
          'grok bot handover', 'Guide', 'ops', 2,
          'From plan-100-v2. Distinct from pto-coverage (plan-50) and share-a-grok-bot.',
          'pto-coverage-for-a-live-grok-bot,share-a-grok-bot'),
        A('multi-tenant-bot-risk', 'Multi-Tenant Risk: Named Bots Do Not Split Clients',
          'multi tenant grok bot', 'Safety', 'ops', 1,
          'From plan-100-v2. Distinct from agencies-isolation and consultants.',
          'grok-bot-for-agencies-isolation,grok-bot-for-consultants-client-isolation'),
        A('compliance-and-ai-agents', 'Compliance Questions Grok Bot Cannot Answer With a Badge',
          'grok bot compliance', 'Safety', 'ops', 2,
          'From plan-100-v2. Distinct from regulated-industries. No invented SOC2/HIPAA.',
          'grok-bot-regulated-industries,prove-grok-bot-to-a-risk-committee'),
        A('bot-change-management', 'Change Management for a Charter Edit That Can Send',
          'grok bot change management', 'Guide', 'ops', 2,
          'From plan-100-v2. Distinct from versioning-and-rollback and review-fatigue.',
          'bot-versioning-and-rollback,grok-bot-review-fatigue'),
        A('bot-escalation-paths', 'Escalation Paths When the Heartbeat File Is Missing',
          'grok bot escalation', 'Guide', 'ops', 2,
          'From plan-100-v2. Distinct from on-call and runbook.',
          'grok-bot-on-call,grok-bot-runbook'),
        A('bot-post-mortems', 'Write a Bot Post-Mortem Without an Audit Log',
          'grok bot post mortem', 'Guide', 'ops', 2,
          'From plan-100-v2. Distinct from no-audit-log-yet and incident-response.',
          'grok-bot-no-audit-log-yet,bot-incident-response'),
        A('bot-setup-checklist', 'A Setup Checklist That Can Fail Before Mail Connect',
          'grok bot setup checklist', 'Guide', 'getting-started', 3,
          'From plan-100-v2. Distinct from preflight-checklist (mail) and setup-guide.',
          'grok-bot-preflight-checklist,grok-bot-setup-guide'),
        A('common-bot-questions', 'Common Grok Bot Questions That Are Usually a Different Product',
          'grok bot faq common', 'Reference', 'getting-started', 3,
          'From plan-100-v2. Distinct from what-is-a-grok-bot and vs-grok-build.',
          'what-is-a-grok-bot,grok-bot-vs-grok-build'),
        A('bot-trial-run-method', 'A Trial Run Method That Does Not Burn the Week on a Five-Minute Loop',
          'grok bot trial run method', 'Guide', 'getting-started', 2,
          'From plan-100-v2. Distinct from how-to-test-on-trial and shadow-mode.',
          'how-to-test-a-grok-bot-on-trial,grok-bot-shadow-mode'),
        A('bot-vocabulary-for-managers', 'Bot Vocabulary for Managers: Computer, Screen, Routine, Approval',
          'grok bot vocabulary managers', 'Guide', 'getting-started', 3,
          'From plan-100-v2. Distinct from explain-to-boss and bot-glossary.',
          'explain-grok-bot-to-your-boss,bot-glossary'),
        A('running-bots-as-a-team', 'Running Bots as a Team When Routines Are Not Team-Level',
          'running grok bots as a team', 'Guide', 'ops', 2,
          'From plan-100-v2. Distinct from teams-standard and share-a-grok-bot.',
          'grok-bot-teams-standard,share-a-grok-bot'),
        A('india-start-plan-and-grok-bot', 'Cursor Start in India and Grok Bot: Confirm the Invoice Line',
          'grok bot cursor start india', 'Guide', 'access', 2,
          'Documented: India-only Start at Rs 649/mo. Do not invent whether it includes Bot. Confirm live.',
          'cheapest-way-into-grok-bot,grok-bot-hobby-and-pro-exclusion'),
        A('cursor-ultra-and-grok-bot', 'Cursor Ultra and Grok Bot: Eligibility Is Not a Private Computer',
          'grok bot cursor ultra', 'Guide', 'access', 2,
          'Ultra $200 includes Bot. Distinct from cursor-pro-plus ($60) and teams-standard.',
          'grok-bot-cursor-pro-plus,cheapest-way-into-grok-bot'),
        A('cursor-teams-premium-and-grok-bot', 'Cursor Teams Premium: $120 Seat, Still One Computer Per Person',
          'grok bot teams premium', 'Guide', 'access', 2,
          'Premium $120/user includes. Distinct from teams-standard $40.',
          'grok-bot-teams-standard'),
        A('supergrok-heavy-eligibility-without-a-price', 'SuperGrok Heavy Includes Bot: Do Not Invent the Price',
          'grok bot super grok heavy', 'Guide', 'access', 2,
          'Eligible. Never print $300. Distinct from supergrok-plus.',
          'grok-bot-supergrok-plus'),
        A('teach-by-demo-is-not-a-charter', 'A Ten-Minute Demo Produces a Draft Skill, Not a Charter',
          'grok bot demonstration vs charter', 'Guide', 'how-to', 2,
          'Distinct from teach-grok-bot-by-demonstration and charter-2026. Demo is browser only, no mic, not iPhone.',
          'teach-grok-bot-by-demonstration,how-to-write-a-grok-bot-charter-2026'),
        A('local-computer-approvals-are-not-undo', 'Local Computer Approvals Do Not Reverse Completed Work',
          'grok bot local computer approval', 'Safety', 'architecture', 1,
          'topics-grok-100 leftover. Distinct from how-to-set-approvals and not-a-sandbox.',
          'how-to-set-grok-bot-approvals,grok-bot-approval-rules-reversibility'),
        A('coming-soon-kill-is-not-shipped', 'Admin Kill Is Coming Soon: VM Goes, Durable Storage Stays',
          'grok bot admin kill', 'Reference', 'architecture', 3,
          'Documented coming soon. Distinct from retirement and delete-safely.',
          'grok-bot-retirement,delete-a-grok-bot-safely'),
        A('team-ceiling-on-local-execution-not-shipped', 'A Team Ceiling on Local Execution Is Not Shipped Yet',
          'grok bot team execution ceiling', 'Reference', 'architecture', 3,
          'Coming soon: Never / Ask / Always, members can only go stricter. Distinct from teams-standard.',
          'grok-bot-teams-standard,how-to-set-grok-bot-approvals'),
        A('no-model-picker-means-billing-follows-failover', 'No Model Picker: Billing Follows the Serving Model',
          'grok bot no model picker', 'Guide', 'access', 2,
          'Documented. Distinct from on-demand-usage and weekly-allowance. Never say grok-4.6 runs Bot.',
          'grok-bot-on-demand-usage,grok-bot-weekly-allowance'),
        A('spacexai-and-who-owns-cursor', 'SpaceXAI, xAI, and Cursor: Who Acquired Whom',
          'spacexai grok bot cursor', 'Guide', 'access', 3,
          'SpaceX acquired xAI, then Anysphere. Do not say xAI acquired Cursor.',
          'grok-bot-cursor-account-explained'),
        A('grok-bot-beta-launch-date', 'Grok Bot Launched 11 August 2026: What That Does Not Mean',
          'when did grok bot launch', 'Reference', 'getting-started', 3,
          'Beta 11 Aug, eligibility widened 21 Aug. Distinct from free-trial.',
          'grok-bot-free-trial,what-is-a-grok-bot'),

        # --- troubleshooting one-symptom leftovers ---
        A('grok-bot-wrong-account-signed-in', 'The Bot Is Signed Into the Wrong Vendor Account',
          'grok bot wrong account', 'Reference', 'troubleshooting', 1,
          'Distinct from login-failed (Cursor auth) and someone-elses-dashboard (cookie inheritance).',
          'grok-bot-login-failed,why-is-this-grok-bot-in-someone-elses-dashboard'),
        A('grok-bot-captcha-wall', 'A Captcha Wall Is a Human Job, Not a Retry Loop',
          'grok bot captcha', 'Reference', 'troubleshooting', 2,
          'Distinct from stalled, 2fa-prompt, static-egress-ip.',
          'grok-bot-stalled,grok-bot-static-egress-ip,grok-bot-2fa-prompt'),
        A('grok-bot-session-expired-mid-routine', 'Session Expired Mid-Routine: Do Not Re-Send',
          'grok bot session expired', 'Reference', 'troubleshooting', 2,
          'Distinct from cannot-send-email and stalled.',
          'grok-bot-cannot-send-email,grok-bot-stalled'),
        A('grok-bot-duplicate-drafts', 'Duplicate Drafts Mean the Routine Fired Twice or the Human Did',
          'grok bot duplicate drafts', 'Reference', 'troubleshooting', 2,
          'Distinct from retire-the-automation-you-replaced (plan-50) and false-positives.',
          'retire-the-automation-you-replaced,grok-bot-false-positives'),
        A('grok-bot-timezone-miss', 'The Routine Ran in the Wrong Timezone',
          'grok bot timezone', 'Reference', 'troubleshooting', 3,
          'Distinct from schedule-routine and routine-did-not-run. Do not invent timezone UI labels.',
          'how-to-schedule-a-grok-bot-routine,grok-bot-routine-did-not-run'),
        A('grok-bot-too-many-routines', 'You Hit 50 Routines on One Bot',
          'grok bot max 50 routines', 'Reference', 'troubleshooting', 2,
          'Documented cap. Distinct from capacity-planning (ops) and schedule-routine.',
          'bot-capacity-planning,how-to-schedule-a-grok-bot-routine'),
        A('grok-bot-history-only-shows-20', 'The App Kept 20 Run Records and You Needed the 21st',
          'grok bot 20 run records', 'Reference', 'troubleshooting', 2,
          'Documented. Distinct from no-audit-log-yet and runbook.',
          'grok-bot-no-audit-log-yet,grok-bot-runbook'),
        A('grok-bot-plugin-signed-in-but-job-used-browser', 'The Plugin Is Signed In and the Job Still Used the Browser',
          'grok bot plugin vs browser', 'Reference', 'troubleshooting', 2,
          'Distinct from plugin-missing and mcp-servers.',
          'grok-bot-plugin-missing,grok-bot-mcp-servers'),

        # --- migration extras ---
        A('move-a-chatgpt-gpt-to-a-grok-bot', 'Move a Custom GPT Into a Grok Bot Charter Without Importing Send',
          'move chatgpt gpt to grok bot', 'Migration', 'migration', 2,
          'Distinct from vs-chatgpt-work and vs-gemini-gems. No import button claimed.',
          'grok-bot-vs-chatgpt-work,how-to-write-a-grok-bot-charter-2026'),
        A('move-a-claude-project-to-a-grok-bot', 'Move a Claude Project Into a Grok Bot Without Pretending It Reads CLAUDE.md',
          'move claude project to grok bot', 'Migration', 'migration', 2,
          'CLAUDE.md is Grok Build. Distinct from vs-claude-cowork and vs-claude-code.',
          'grok-bot-vs-claude-cowork,grok-bot-vs-claude-code'),
        A('move-a-gemini-gem-to-a-grok-bot', 'Move a Gemini Gem Into a Grok Bot: Names Persist, Computers Do Not',
          'move gemini gem to grok bot', 'Migration', 'migration', 3,
          'Distinct from vs-gemini-gems.',
          'grok-bot-vs-gemini-gems'),
        A('move-lindy-skills-to-a-grok-bot', 'Move a Lindy Workflow Idea Into a Grok Bot Charter, Confirm Lindy Live',
          'move lindy to grok bot', 'Migration', 'migration', 3,
          'Hedge Lindy. Distinct from vs-lindy and move-a-zap.',
          'grok-bot-vs-lindy,move-a-zap-to-a-bot'),
        A('copy-a-botskills-listing-onto-a-second-seat', 'Copy a Listing Onto a Second Eligible Seat, Then Sign Out the First Computer',
          'copy grok bot to another seat', 'Migration', 'migration', 1,
          'No documented transfer. Distinct from personal-to-work and share-a-grok-bot.',
          'move-grok-bot-work-from-personal-to-work,share-a-grok-bot'),
        A('hand-a-contractor-the-charter-not-the-login', 'Hand a Contractor the Charter, Never the Cursor Login',
          'share grok bot with contractor', 'Safety', 'ops', 1,
          'Distinct from share-a-grok-bot (intern) and agencies-isolation. Login shares the computer.',
          'share-a-grok-bot,grok-bot-for-agencies-isolation'),
        A('pause-the-roster-before-you-travel', 'Pause Every Routine Before You Travel, Because iPhone Cannot Edit',
          'pause grok bot before travel', 'Guide', 'ops', 2,
          'Distinct from pto-coverage, on-call, and pause-on-iphone (click path). This is the travel checklist.',
          'pto-coverage-for-a-live-grok-bot,how-to-pause-a-grok-bot-on-iphone'),
        A('stale-heartbeat-file-is-a-fail', 'A Heartbeat File From Yesterday Is a Failed Run',
          'grok bot stale heartbeat', 'Guide', 'ops', 2,
          'Distinct from runbook (overnight empty) and false-positives (always red). Quiet week still needs a dated file.',
          'grok-bot-runbook,grok-bot-false-positives'),
        A('vendor-renewal-memo-never-signs', 'Draft a Vendor Renewal Memo, Never Sign the Order Form',
          'grok bot vendor renewal', 'Tutorial', 'jobs', 2,
          'Distinct from trust-center-answers and expense-manager. Signature is irreversible.',
          'trust-center-answers-never-send-the-packet,grok-bot-for-finance-teams-never-pay'),
        A('read-only-bank-view-then-sign-out', 'Use a Read-Only Bank View, Then Sign Out of the Shared Computer',
          'grok bot read only bank', 'Safety', 'jobs', 1,
          'Distinct from personal-cfo-brief and 2fa-prompt. 2FA into a bank is a house key.',
          'personal-cfo-brief-never-moves-money,grok-bot-2fa-prompt'),
        A('screenshot-pack-is-not-a-live-price', 'A Screenshot Pack Is Not Today\'s Price',
          'grok bot screenshot vs live price', 'Guide', 'ops', 2,
          'Distinct from evidence-rules and competitor-pricing-watch. Yesterday\'s PNG is stale.',
          'grok-bot-evidence-rules,competitor-pricing-watch-never-reprices'),
        A('public-wifi-does-not-pause-the-cloud-computer', 'Public Wi-Fi Does Not Pause the Cloud Computer',
          'grok bot public wifi', 'Guide', 'architecture', 3,
          'Distinct from runs-with-laptop-closed. Closing a cafe lid does not stop routines.',
          'grok-bot-runs-with-laptop-closed,how-to-pause-a-grok-bot-on-iphone'),
        A('family-apple-id-is-not-a-grok-bot-seat', 'A Family Apple ID Is Not a Grok Bot Seat',
          'grok bot family apple id', 'Guide', 'access', 3,
          'Distinct from iphone-app and teams-standard. Eligibility is Cursor or xAI, not Family Sharing.',
          'grok-bot-iphone-app,grok-bot-teams-standard'),
    ]


def main() -> None:
    live = live_slugs()
    held = held_slugs()
    blocked = live | held
    live_tok = {s: toks(s) for s in live}

    rows = from_plan50() + extra_topics()
    seen = set()
    kept = []
    dropped = []
    for a in rows:
        slug = a['slug']
        if slug in seen:
            dropped.append((slug, 'dup-in-plan'))
            continue
        if slug in blocked:
            dropped.append((slug, 'live-or-held'))
            continue
        st = toks(slug)
        hit = None
        best = 0.0
        for ls, lt in live_tok.items():
            j = jaccard(st, lt)
            if j > best:
                best, hit = j, ls
        if best >= 0.55:
            dropped.append((slug, f'jaccard {best:.2f} vs {hit}'))
            continue
        seen.add(slug)
        kept.append(a)

    # If short of 250, we fail loudly so a human adds more unique intents.
    if len(kept) > 250:
        kept.sort(key=lambda a: (a['priority'], a['slug']))
        extra = kept[250:]
        kept = kept[:250]
        print('trimmed to 250, removed', [a['slug'] for a in extra])
    payload = {
        'generated': '2026-08-28',
        'count': len(kept),
        'target': 250,
        'method': (
            'plan-50 (51 collision-cleared intents from 2026-08-27) plus catalog-bot jobs, '
            'integrations with a unique never-line, hedged comparisons, leftover plan-100-v2 ops, '
            'and migrations. Live corpus slugs and held-duplicates are blocked. Slug-token Jaccard '
            '>= 0.55 against a live slug is dropped. Rakazo is excluded until VERIFIED-FACTS covers it. '
            'Product facts only from docs/seo/VERIFIED-FACTS-2026-08-25.md. LONGFORM-SPEC and HUMANIZE-SPEC.'
        ),
        'note': (
            'Grok Bot long-tail plan. Skip any slug that later appears in packages/web/src/app/blog/posts. '
            'Do not write a page that remakes a live twin named in distinct_from. Third-party products are '
            'hedged to the vendor page. Never invent allowance dollars, SuperGrok Heavy $300, or a Linux app.'
        ),
        'live_corpus_at_plan': len(live),
        'dropped': [{'slug': s, 'reason': r} for s, r in dropped],
        'articles': kept,
    }
    OUT.write_text(json.dumps(payload, indent=1) + '\n')
    print(f'wrote {OUT} count={len(kept)} dropped={len(dropped)} live={len(live)}')
    if len(kept) < 250:
        print('SHORT: need', 250 - len(kept), 'more unique intents')
    elif len(kept) > 250:
        print('LONG: trim', len(kept) - 250)
    by = {}
    for a in kept:
        by[a['cluster']] = by.get(a['cluster'], 0) + 1
    print('clusters', dict(sorted(by.items(), key=lambda kv: -kv[1])))
    if dropped:
        print('dropped sample:')
        for s, r in dropped[:15]:
            print(f'  {s}: {r}')


if __name__ == '__main__':
    main()
