#!/usr/bin/env python3
"""Generate one article registry, refusing to publish if validation fails.

Run without arguments to write index.ts, or with --check for a read-only CI
check. The output is deterministic and unchanged files are never rewritten.
"""
import argparse
from pathlib import Path
import re
import subprocess
import sys
import tempfile

HERE = Path(__file__).resolve().parent
POSTS = HERE.parent / 'packages/web/src/app/blog/posts'
PINNED = ('introducing-botskills', 'one-person-company-grok-bot')


def render_registry(slugs):
    if len(slugs) != len(set(slugs)):
        raise ValueError('Duplicate article slug')
    if not slugs:
        raise ValueError('Cannot publish an empty article registry')
    for slug in slugs:
        if not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', slug):
            raise ValueError(f'Invalid article slug: {slug}')
    order = [s for s in PINNED if s in slugs]
    order += sorted(s for s in slugs if s not in PINNED)
    lines = [
        '// Generated by scripts/register.py. Run it after adding or editing articles.',
        '// The page lookup, blog index and sitemap derive from the same entries.',
        "import { createBlogRegistry } from '../../../lib/blog-registry';",
        "export type { BlogPost } from '../../../lib/blog-registry';",
        '',
    ]
    def alias(slug):
        return 'post_' + slug.replace('-', '_')

    lines += [f"import {{ post as {alias(slug)} }} from './{slug}';" for slug in order]
    lines += ['', 'export const { posts, postList } = createBlogRegistry([']
    lines += [f"  {{ slug: '{slug}', ...{alias(slug)} }}," for slug in order]
    lines += [']);', '']
    return '\n'.join(lines)


def register(posts_dir=POSTS, *, check=False, run_gate=None):
    slugs = sorted(p.stem for p in posts_dir.glob('*.ts') if p.name != 'index.ts')
    generated = render_registry(slugs)
    if run_gate is None:
        result = subprocess.run(
            [sys.executable, str(HERE / 'gate.py'), *slugs],
            capture_output=True, text=True, check=False,
        )
    else:
        result = run_gate(slugs)
    # Any failure, including a crashed validator, leaves the live registry intact.
    checked = set(re.findall(
        r'^(\S+)\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+OK(?: \(exempt\))?$',
        result.stdout, re.MULTILINE,
    ))
    if result.returncode != 0 or checked != set(slugs):
        print(result.stdout, end='', file=sys.stderr)
        print(result.stderr, end='', file=sys.stderr)
        raise RuntimeError('Article gate failed or did not check every article; registry was not changed')
    target = posts_dir / 'index.ts'
    current = target.read_text(encoding='utf-8') if target.exists() else None
    if current == generated:
        print(f'registry current: {len(slugs)} articles')
        return 0
    if check:
        print('Registry is out of date. Run python3 scripts/register.py.', file=sys.stderr)
        return 1
    # Publish the entire generated file atomically after all checks have passed.
    with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=posts_dir,
                                     prefix='.registry-', suffix='.tmp', delete=False) as tmp:
        tmp.write(generated)
        temp_path = Path(tmp.name)
    try:
        temp_path.chmod(0o644)
        temp_path.replace(target)
    finally:
        temp_path.unlink(missing_ok=True)
    print(f'registered {len(slugs)} articles')
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        return register(check=args.check)
    except (ValueError, RuntimeError, OSError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
